import './Mascot.css';

/**
 * Available mascot poses. Each maps to variants in /public/mascot/
 * (générées depuis assets-src/mascot/ par scripts/process-mascots.mjs).
 */
export const MASCOT_POSES = {
  reading:     { num: 1,  alt: 'Cerveau qui lit un livre' },
  flashcard:   { num: 2,  alt: 'Cerveau présentant une flashcard' },
  celebration: { num: 3,  alt: 'Cerveau qui fête la victoire' },
  sleeping:    { num: 4,  alt: 'Cerveau endormi' },
  thinking:    { num: 5,  alt: 'Cerveau en pleine réflexion' },
  writing:     { num: 6,  alt: 'Cerveau qui prend des notes' },
  trophy:      { num: 7,  alt: 'Cerveau avec un trophée' },
  confused:    { num: 8,  alt: 'Cerveau confus' },
  hello:       { num: 9,  alt: 'Cerveau qui dit bonjour' },
  scan:        { num: 11, alt: 'Cerveau qui scanne avec un téléphone' },
  fire:        { num: 12, alt: 'Cerveau en feu, motivé' },
  graduation:  { num: 13, alt: 'Cerveau diplômé' },
  sad:         { num: 14, alt: 'Cerveau triste' },
  search:      { num: 15, alt: 'Cerveau avec une loupe' },
  pointing:    { num: 16, alt: 'Cerveau qui pointe du doigt' },

  // --- Matières (série 2026-08, cf. assets-src/mascot/BRIEF-MASCOTTES.md) ---
  maths:       { num: 'm1', alt: 'Cerveau matheux avec compas et règle' },
  francais:    { num: 'm2', alt: 'Cerveau plongé dans un roman' },
  svt:         { num: 'm3', alt: 'Cerveau naturaliste avec loupe et ADN' },
  physique:    { num: 'm4', alt: 'Cerveau chimiste avec sa fiole' },
  histgeo:     { num: 'm5', alt: 'Cerveau explorateur avec son globe' },
  langues:     { num: 'm6', alt: 'Cerveau polyglotte au casque audio' },
  technonsi:   { num: 'm7', alt: 'Cerveau codeur sur son laptop' },
  philo:       { num: 'm8', alt: 'Cerveau penseur assis sur ses livres' },
  arts:        { num: 'm9', alt: 'Cerveau artiste avec sa palette' },

  // --- Situations (série 2026-08) ---
  quiz:        { num: 's1', alt: 'Cerveau qui appuie sur un buzzer' },
  coach:       { num: 's2', alt: 'Coach Réviz avec son casque-micro' },
  levelup:     { num: 's3', alt: 'Cerveau qui décolle vers le niveau supérieur' },
  retour:      { num: 's4', alt: 'Cerveau qui accueille à bras ouverts' },
  soir:        { num: 's5', alt: 'Cerveau en révision du soir' },
  examen:      { num: 's6', alt: 'Cerveau fier de sa copie étoilée' },
  scanphone:   { num: 's7', alt: 'Cerveau qui photographie une leçon' },
  muscu:       { num: 's8', alt: 'Cerveau qui muscle sa mémoire' },
};

/**
 * Build the asset base URL for a given pose, picking the smallest variant
 * that still looks crisp at the requested rendered size (accounting for DPR).
 * DPR is capped at 2: at mascot sizes, the @512 variant is already
 * indistinguishable on DPR-3 screens and the full-size PNG pèse ~1 Mo.
 */
function getMascotBase(pose, size) {
  const meta = MASCOT_POSES[pose];
  if (!meta) return null;
  const rawDpr = typeof window !== 'undefined' ? window.devicePixelRatio || 1 : 2;
  const targetPx = size * Math.min(rawDpr, 2);
  // Variants available: @256, @512 (PNG + WebP), generated by scripts/process-mascots.mjs.
  const variant = targetPx <= 256 ? '@256' : '@512';
  return `/mascot/pose-${meta.num}-${pose}${variant}`;
}

/**
 * Réviz brand mascot — a cute brain character in various poses.
 *
 * @param {object} props
 * @param {keyof typeof MASCOT_POSES} props.pose       — required, the pose name
 * @param {number} [props.size=256]                    — rendered size in px (square)
 * @param {boolean} [props.glow=false]                 — apply the signature orange glow
 * @param {number} [props.glowIntensity=0.55]          — 0–1, glow opacity
 * @param {number} [props.glowRadius]                  — px, defaults to size * 0.1
 * @param {boolean} [props.priority=false]             — eager-load (above-the-fold)
 * @param {boolean} [props.animate=false]              — gentle floating animation
 * @param {string}  [props.alt]                        — override default alt text
 * @param {string}  [props.className]                  — extra classes on the wrapper
 * @param {object}  [props.style]                      — inline styles merged with size
 */
export function Mascot({
  pose,
  size = 256,
  glow = false,
  glowIntensity = 0.55,
  glowRadius,
  priority = false,
  animate = false,
  alt,
  className = '',
  style,
  ...rest
}) {
  const meta = MASCOT_POSES[pose];
  if (!meta) {
    if (import.meta.env?.DEV) {
      console.warn(`<Mascot pose="${pose}"> — unknown pose. Available:`, Object.keys(MASCOT_POSES));
    }
    return null;
  }

  const base = getMascotBase(pose, size);
  const radius = glowRadius ?? Math.round(size * 0.1);

  const mergedStyle = {
    width: size,
    height: size,
    '--mascot-glow-radius': `${radius}px`,
    '--mascot-glow-intensity': glowIntensity,
    ...style,
  };

  const classes = [
    'mascot',
    glow && 'mascot--glow',
    animate && 'mascot--animate',
    className,
  ].filter(Boolean).join(' ');

  return (
    // display:contents : le <picture> ne génère pas de boîte, l'<img> reste
    // l'élément stylé/flexé par les classes des pages (flex-shrink, align-self…).
    <picture style={{ display: 'contents' }}>
      <source srcSet={`${base}.webp`} type="image/webp" />
      <img
        src={`${base}.png`}
        alt={alt ?? meta.alt}
        width={size}
        height={size}
        loading={priority ? 'eager' : 'lazy'}
        decoding="async"
        fetchpriority={priority ? 'high' : 'auto'}
        draggable={false}
        className={classes}
        style={mergedStyle}
        {...rest}
      />
    </picture>
  );
}
